### PR TITLE
Ability to import image as static ground object

### PR DESCRIPTION
**Pull request by marius851000**
The main change in pmd_wan 2.0.0 is support for writing wan file, thought this doesn't expose it yet. My goal is to be able to import png as unanimated object sprite. This new version also does some changes in the API, to be closer to the original file format without making it much harder to use it.

### CODE REVIEW

**Comment by marius851000** [comment]
Oh. And I'll change the skytemple-files too, still to be done

**Comment by marius851000** [comment]
The new pmd_wan version break the API, so the three changes above need to be merged together.

**Comment by marius851000** [comment]
I will soon make a new version with some other changes, and it will have some function to create wan files.

**Comment by marius851000** [comment]
Now I need to update the two other patches

**Comment by marius851000** [comment]
And auto-set this unk2 to something that is not 512

**Comment by marius851000** [comment]
Done ! Should work now.

**Comment by theCapypara** [comment]
Hi! It would be amazing if you could rebase all your branches on the current main/masters and make sure checks and tests pass.
I'll also do some rework for some things after that for things I did for the Rust extensions for Kao and stuff and how they are accessed from SkyTemple in the future. This way you don't have to do it but we are future proof and I'll show you what I did.

**Comment by marius851000** [comment]
Well... About checks... They probably wont pass due to incompatibility. But I'll try to run them locally. Also, I fixed an issue where :
1. It always allocated at least 512 block of memory.
2. It always allocated 256 color in the palette. (causing some issues)

**Comment by theCapypara** [comment]
Thanks a lot!!!

**Pull request merged**
